### ISSUE TITLE
Interactive highlight doesn't follow tool when first grabbed with touch

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/geometric-optics-basics#29] opened 2022-11-03 16:21 UTC
**Test device**
iPad (9th generation)

**Operating System**
iOS 16

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/847, when grabbing a tool from the panel, the interactive highlight size doesn't change or move with the tool. Once you release the tool and grab it again, it works correctly. 
I didn't see this issue on my mac with safari/chrome, only on the iPad. 

**Steps to reproduce**
1. Turn on interactive highlights
2. Grab a ruler from the panel and move it into the play area. 

**Visuals**

https://user-images.githubusercontent.com/87318828/199776029-00583579-5895-4d40-a86c-0cff6c2b0b4f.MP4

Here is what it looks like on my mac:

https://user-images.githubusercontent.com/87318828/199775254-3b28af80-7e53-4e75-8a95-f7126ea1f00d.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Geometric Optics: Basics‬
URL: https://phet-dev.colorado.edu/html/geometric-optics-basics/1.2.0-dev.3/phet/geometric-optics-basics_all_phet.html
Version: 1.2.0-dev.3 2022-10-31 21:00:48 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1813x1056
Pixel Ratio: 1.3333333730697632/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment] 2022-11-04 00:47
Interactive highlight is a general feature that was added in common code. It looks to me like the implementation did not consider the [Creator (with Drag forwarding)](https://github.com/phetsims/phet-info/blob/master/doc/phet-software-design-patterns.md#creator-with-drag-forwarding) pattern, which is typically used wherever there's a toolbox.


In Geometric Optics, the base class for tools is GOToolNode:

```typescript
export default abstract class GOToolNode extends InteractiveHighlighting( Node ) {
```

The base class for icons associated with tools (the icons that appear in the toolbox) is GOToolIcon:

```
export default abstract class GOToolIcon extends InteractiveHighlighting( Node ) {
```

When an icon in the toolbox is clicked, it makes itself invisible, makes its associated full-size tool visible, and calls `DragListener.createForwardingListener` to forward drag listeners. Relevant code in GOToolIcon.ts:

```typescript
    // Dragging with mouse/touch. Drag events are forwarded from the icon to its associated tool Node.
    this.addInputListener( DragListener.createForwardingListener( ( event: PressListenerEvent ) => {

      // Take the tool out of the toolbox.
      tool.isInToolboxProperty.value = false;

      // Set the position of the tool.
      tool.positionProperty.value = pointerPositionToToolPosition( event.pointer.point );

      // Forward the event to toolNode.
      toolNode.startDrag( event );
    } ) );
```

**Comment by pixelzoom** [comment] 2022-11-07 23:35
QA has completed dev test https://github.com/phetsims/qa/issues/847.  Further progress is blocked until this issue is addressed.  If we wait more than a few days, we'll need to do another dev test, because master will have diverged.

**Comment by jessegreenberg** [comment] 2022-11-08 19:30
This should be fixed with the above commit. Basically certain things were not being reset on `exit` events when toolbar icons became invisible. So this wasn't so much an issue with forwarding a drag listener but more exit events in general.

@Nancy-Salpepi can you please test master and confirm this is fixed?

**Comment by Nancy-Salpepi** [comment] 2022-11-08 20:22
It is indeed fixed @jessegreenberg!

**Comment by pixelzoom** [comment] 2022-11-08 20:54
I also confirmed that it's fixed in master. Thanks @jessegreenberg. Closing.

**Closed by pixelzoom** 2022-11-08 20:54 UTC
Labels: type:bug, status:blocks-publication
